name: Setup Rust
description: Set up a compilable Rust workspace

runs:
  using: composite
  steps:
    - name: Set cargo env vars
      shell: bash
      run: echo "CARGO_TERM_COLOR=always" >> "$GITHUB_ENV"

    - uses: dtolnay/rust-toolchain@stable
      id: rust-toolchain
      with:
        components: clippy, rustfmt

    - uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-${{ runner.os }}-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-${{ runner.os }}-${{ steps.rust-toolchain.outputs.cachekey }}-
